### PR TITLE
the shrinker will warn on provided indirect targets if they are used …

### PR DESCRIPTION
**Pull request by natansil**
…in compilation

@ittaiz @or-shachar

### CODE REVIEW

**Comment by natansil** [comment]
@nadavwe

**Comment by jvican** [comment]
@natansil? Is there any reason why you closed this?

**Comment by natansil** [comment]
@jvican , this PR was done by mistake. We altered the plugin quite a lot in order to make it useful for building with bazel.
You can take a look at this [PR](https://github.com/bazelbuild/rules_scala/pull/243) for the `rules_scala` repo. we put the plugin code in a separate ['third_party' directory](https://github.com/bazelbuild/rules_scala/pull/243/files#diff-829c80b08fc7a4553b83c4a055a98069) with a BSD-3 license [file](https://github.com/bazelbuild/rules_scala/pull/243/files#diff-54ecc73cc85d080d0e56b618ccd74de1)...

**Comment by jvican** [comment]
Okay, please keep me in the loop with that. The Center is always interested to know where our work is reused :smile:.
  
I don't quite get the changes that you proposed here. But is there something that we can merge upstream so that the rest of the users of this plugin benefit? Or are your changes Bazel-specific?

**Comment by natansil** [comment]
the changes are quite bazel-specific in the sense that they make the plugin expect to get `bazel` targets labels in order to notify the users which target labels they need to add to direct dependencies

**Comment by ittaiz** [comment]
They are generic in the sense that Pants could benefit from it too since
they have similar concepts but since the plugin and the build tool needs to
agree on the format of the inputs I'm not sure it's that practical.

**Pull request closed without merging**
