### PR TITLE
use modern coursier (and other modern things too)

### PR DESCRIPTION
**Pull request by SethTisue**
the main goal here is the coursier version bump, because
we want to include classpath-shrinker in the Scala community build,
and coursier is on a more modern version there

the other version bumps are just gravy

the change to ClassPathFeedback.scala is to fix test failures (induced by the coursier version bump) such
as the following:

```
[error] Detected the following unused classpath entries:
[error] /Users/tisue/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/guava/guava/21.0/guava-21.0.jar
[error] Expected:
[error] Detected the following unused classpath entries:
[error] /Users/tisue/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/guava/guava/21.0/guava-21.0.jar
[error] /Users/tisue/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/guava/guava/21.0/guava-21.0.pom
```

references https://github.com/scala/community-builds/pull/770

### CODE REVIEW

**Comment by SethTisue** [comment]
@jvican the Drone failure looks like your dept...?

**Comment by SethTisue** [comment]
added another commit that moves to an even newer coursier; this came up in the context of https://github.com/scala/community-builds/pull/765

**Comment by SethTisue** [comment]
note that I don't actually know what I'm doing with coursier and scalaz-concurrent, I just fooled with it until it compiled and the tests pass. it's probably good enough?

**Review by jvican — APPROVED** [review]
Indeed thanks Seth!

**Comment by jvican** [comment]
I’ll have a look at why the tests fail in the CI on Thursday since I’m on vacation during the next three days.

**Comment by SethTisue** [comment]
@jvican nbd, but: ping

**Comment by SethTisue** [comment]
@jvican ping

**Comment by jvican** [comment]
Hey Seth, I’m a little bit busy for the next week and a half to get back to this, can we get back to it then? If so I’ll add it to my calendar.

**Comment by SethTisue** [comment]
sure, there's no particular rush, having classpath-shrinker in the community build is desirable, but not urgent

**Comment by SethTisue** [comment]
@jvican ping

**Comment by SethTisue** [comment]
@jvican ping

**Comment by jvican** [comment]
@SethTisue realistically speaking I won't have time for this any time soon. it looks like I'll need to manually fix the CI because the drone image used here doesn't exist anymore. I propose we don't add classpath-shrinker to the community build for now...

**Comment by SethTisue** [comment]
> I propose we don't add classpath-shrinker to the community build for now

it's already there, but using a fork. it can stay that way, if it ever acts up I'll just get rid of it. scala/community-builds@5dba764e3385e7dd45f0ff494a93c96343a4975a

**Pull request closed without merging**
